"""Private input boundary. Domain services depend on this, never a vendor API."""

from typing import Protocol
import numpy as np


class InputBackend(Protocol):
    def ready(self) -> bool: ...
    def begin(self, timeout: float) -> None: ...
    def check(self) -> None: ...
    def capture(self) -> np.ndarray: ...
    def click(self, point: tuple[int, int], *, button: str = "left") -> None: ...
    def key(self, key: str) -> None: ...
    def scroll(self, point: tuple[int, int], delta: int) -> None: ...
    def release(self) -> None: ...
    def end(self) -> None: ...
